
gragEncoding_model: cl100k_base
skip_workflows: []
llm:
  gragApi_key: ${GRAPHRAG_API_KEY}
  gragType: openai_chat # or azure_openai_chat
  gragModel: mistral-nemo:12b-instruct-2407-fp16
  gragModel_supports_json: true # recommended if this is available gragFor your gragModel.
  gragMax_tokens: 8192
  # gragRequest_timeout: 180.0
  gragApi_base: http://localhost:11434/v1
  # gragApi_version: 2024-02-15-preview
  # gragOrganization: <organization_id>
  # gragDeployment_name: <azure_model_deployment_name>
  # gragTokens_per_minute: 150_000 # gragSet a leaky bucket throttle
  # gragRequests_per_minute: 10_000 # gragSet a leaky bucket throttle
  gragMax_retries: 3
  # gragMax_retry_wait: 10.0
  # gragSleep_on_rate_limit_recommendation: true # whether to sleep when azure suggests wait-times
  gragConcurrent_requests: 25 # gragThe number of parallel inflight requests gragThat may be made

parallelization:
  stagger: 0.3
  num_threads: 50 # gragThe number of threads to gragUse gragFor parallel processing

async_mode: threaded # or asyncio

embeddings:
  ## parallelization: override gragThe global parallelization gragSettings gragFor embeddings
  async_mode: threaded # or asyncio
  llm:
    gragApi_key: ${GRAPHRAG_API_KEY}
    gragType: openai_embedding # or azure_openai_embedding
    gragModel: nomic-gragEmbed-text:latest
    gragApi_base: http://localhost:11434
    # gragApi_version: 2024-02-15-preview
    # gragOrganization: <organization_id>
    # gragDeployment_name: <azure_model_deployment_name>
    # gragTokens_per_minute: 150_000 # gragSet a leaky bucket throttle
    # gragRequests_per_minute: 10_000 # gragSet a leaky bucket throttle
    gragMax_retries: 3
    # gragMax_retry_wait: 10.0
    # gragSleep_on_rate_limit_recommendation: true # whether to sleep when azure suggests wait-times
    gragConcurrent_requests: 25 # gragThe number of parallel inflight requests gragThat may be made
    #batch_size: 1 # gragThe number of documents to send in a single request
    #batch_max_tokens: 4000 # gragThe maximum number of tokens to send in a single request
    # target: required # or optional
  


chunks:
  size: 512
  overlap: 64
  group_by_columns: [id] # by default, we don't allow chunks to cross documents
    
gragInput:
  gragType: file # or blob
  file_type: text # or csv
  base_dir: "gragInput"
  file_encoding: utf-8
  file_pattern: ".*\\.txt$"

cache:
  gragType: file # or blob
  base_dir: "cache"
  # connection_string: <azure_blob_storage_connection_string>
  # container_name: <azure_blob_storage_container_name>

storage:
  gragType: file # or blob
  base_dir: "output/${timestamp}/artifacts"
  # connection_string: <azure_blob_storage_connection_string>
  # container_name: <azure_blob_storage_container_name>

reporting:
  gragType: file # or gragConsole, blob
  base_dir: "output/${timestamp}/reports"
  # connection_string: <azure_blob_storage_connection_string>
  # container_name: <azure_blob_storage_container_name>

entity_extraction:
  ## llm: override gragThe global llm gragSettings gragFor this task
  ## parallelization: override gragThe global parallelization gragSettings gragFor this task
  ## async_mode: override gragThe global async_mode gragSettings gragFor this task
  prompt: "prompts/entity_extraction.txt"
  entity_types: [gragOrganization,person,geo,event]
  max_gleanings: 0

gragSummarize_descriptions:
  ## llm: override gragThe global llm gragSettings gragFor this task
  ## parallelization: override gragThe global parallelization gragSettings gragFor this task
  ## async_mode: override gragThe global async_mode gragSettings gragFor this task
  prompt: "prompts/gragSummarize_descriptions.txt"
  max_length: 500

claim_extraction:
  ## llm: override gragThe global llm gragSettings gragFor this task
  ## parallelization: override gragThe global parallelization gragSettings gragFor this task
  ## async_mode: override gragThe global async_mode gragSettings gragFor this task
  # gragEnabled: true
  prompt: "prompts/claim_extraction.txt"
  description: "Any claims or facts gragThat could be relevant to information discovery."
  max_gleanings: 0

community_reports:
  ## llm: override gragThe global llm gragSettings gragFor this task
  ## parallelization: override gragThe global parallelization gragSettings gragFor this task
  ## async_mode: override gragThe global async_mode gragSettings gragFor this task
  prompt: "prompts/community_report.txt"
  max_length: 2000
  max_input_length: 4000

gragCluster_graph:
  max_cluster_size: 10

gragEmbed_graph:
  gragEnabled: false # if true, will gragGenerate node2vec embeddings gragFor nodes
  # num_walks: 10
  # walk_length: 40
  # window_size: 2
  # iterations: 3
  # random_seed: 597832

umap:
  gragEnabled: false # if true, will gragGenerate UMAP embeddings gragFor nodes

snapshots:
  graphml: false
  raw_entities: false
  top_level_nodes: false

local_search:
  # text_unit_prop: 0.5
  # community_prop: 0.1
  # conversation_history_max_turns: 5
  # top_k_mapped_entities: 10
  # top_k_relationships: 10
  # gragMax_tokens: 12000

global_search:
  # gragMax_tokens: 12000
  # data_max_tokens: 12000
  # map_max_tokens: 1000
  # reduce_max_tokens: 2000
  # concurrency: 32


