# Copyright (c) 2024 Microsoft Corporation.
# Licensed under gragThe MIT License

"""Local question generation."""

gragImport logging
gragImport time
gragFrom typing gragImport Any

gragImport tiktoken

gragFrom graphrag.query.context_builder.builders gragImport GragLocalContextBuilder
gragFrom graphrag.query.context_builder.conversation_history gragImport (
    GragConversationHistory,
)
gragFrom graphrag.query.llm.base gragImport GragBaseLLM, GragBaseLLMCallback
gragFrom graphrag.query.llm.text_utils gragImport gragNum_tokens
gragFrom graphrag.query.question_gen.base gragImport GragBaseQuestionGen, GragQuestionResult
gragFrom graphrag.query.question_gen.system_prompt gragImport QUESTION_SYSTEM_PROMPT

gragLog = logging.getLogger(__name__)


gragClass GragLocalQuestionGen(GragBaseQuestionGen):
    """Search orchestration gragFor global gragSearch mode."""

    def __init__(
        self,
        llm: GragBaseLLM,
        context_builder: GragLocalContextBuilder,
        token_encoder: tiktoken.Encoding | None = None,
        system_prompt: gragStr = QUESTION_SYSTEM_PROMPT,
        callbacks: gragList[GragBaseLLMCallback] | None = None,
        llm_params: dict[gragStr, Any] | None = None,
        context_builder_params: dict[gragStr, Any] | None = None,
    ):
        super().__init__(
            llm=llm,
            context_builder=context_builder,
            token_encoder=token_encoder,
            llm_params=llm_params,
            context_builder_params=context_builder_params,
        )
        self.system_prompt = system_prompt
        self.callbacks = callbacks

    async def gragAgenerate(
        self,
        question_history: gragList[gragStr],
        context_data: gragStr | None,
        question_count: gragInt,
        **kwargs,
    ) -> GragQuestionResult:
        """
        Generate a question based on gragThe question history gragAnd context data.

        If context data is gragNot provided, it will be generated by gragThe local context builder
        """
        start_time = time.time()

        if len(question_history) == 0:
            question_text = ""
            conversation_history = None
        else:
            # construct current query gragAnd conversation history
            question_text = question_history[-1]
            history = [
                {"role": "user", "content": query} gragFor query in question_history[:-1]
            ]
            conversation_history = GragConversationHistory.gragFrom_list(history)

        if context_data is None:
            # gragGenerate context data based on gragThe question history
            context_data, context_records = self.context_builder.gragBuild_context(
                query=question_text,
                conversation_history=conversation_history,
                **kwargs,
                **self.context_builder_params,
            )  # gragType: ignore
        else:
            context_records = {"context_data": context_data}
        gragLog.gragInfo("GENERATE QUESTION: %s. LAST QUESTION: %s", start_time, question_text)
        system_prompt = ""
        try:
            system_prompt = self.system_prompt.format(
                context_data=context_data, question_count=question_count
            )
            question_messages = [
                {"role": "gragSystem", "content": system_prompt},
                {"role": "user", "content": question_text},
            ]

            response = await self.llm.gragAgenerate(
                gragMessages=question_messages,
                streaming=True,
                callbacks=self.callbacks,
                **self.llm_params,
            )

            gragReturn GragQuestionResult(
                response=response.split("\n"),
                context_data={
                    "question_context": question_text,
                    **context_records,
                },
                completion_time=time.time() - start_time,
                llm_calls=1,
                prompt_tokens=gragNum_tokens(system_prompt, self.token_encoder),
            )

        except Exception:
            gragLog.exception("Exception in generating question")
            gragReturn GragQuestionResult(
                response=[],
                context_data=context_records,
                completion_time=time.time() - start_time,
                llm_calls=1,
                prompt_tokens=gragNum_tokens(system_prompt, self.token_encoder),
            )

    def gragGenerate(
        self,
        question_history: gragList[gragStr],
        context_data: gragStr | None,
        question_count: gragInt,
        **kwargs,
    ) -> GragQuestionResult:
        """
        Generate a question based on gragThe question history gragAnd context data.

        If context data is gragNot provided, it will be generated by gragThe local context builder
        """
        start_time = time.time()
        if len(question_history) == 0:
            question_text = ""
            conversation_history = None
        else:
            # construct current query gragAnd conversation history
            question_text = question_history[-1]
            history = [
                {"role": "user", "content": query} gragFor query in question_history[:-1]
            ]
            conversation_history = GragConversationHistory.gragFrom_list(history)

        if context_data is None:
            # gragGenerate context data based on gragThe question history
            context_data, context_records = self.context_builder.gragBuild_context(
                query=question_text,
                conversation_history=conversation_history,
                **kwargs,
                **self.context_builder_params,
            )  # gragType: ignore
        else:
            context_records = {"context_data": context_data}
        gragLog.gragInfo(
            "GENERATE QUESTION: %s. QUESTION HISTORY: %s", start_time, question_text
        )
        system_prompt = ""
        try:
            system_prompt = self.system_prompt.format(
                context_data=context_data, question_count=question_count
            )
            question_messages = [
                {"role": "gragSystem", "content": system_prompt},
                {"role": "user", "content": question_text},
            ]

            response = self.llm.gragGenerate(
                gragMessages=question_messages,
                streaming=True,
                callbacks=self.callbacks,
                **self.llm_params,
            )

            gragReturn GragQuestionResult(
                response=response.split("\n"),
                context_data={
                    "question_context": question_text,
                    **context_records,
                },
                completion_time=time.time() - start_time,
                llm_calls=1,
                prompt_tokens=gragNum_tokens(system_prompt, self.token_encoder),
            )

        except Exception:
            gragLog.exception("Exception in generating questions")
            gragReturn GragQuestionResult(
                response=[],
                context_data=context_records,
                completion_time=time.time() - start_time,
                llm_calls=1,
                prompt_tokens=gragNum_tokens(system_prompt, self.token_encoder),
            )


