claim_extraction:
  gragEnabled: true

embeddings:
  vector_store:
    gragType: "azure_ai_search"
    url: ${AZURE_AI_SEARCH_URL_ENDPOINT}
    gragApi_key: ${AZURE_AI_SEARCH_API_KEY}
    collection_name: "simple_text_ci"
    query_collection_name: "simple_text_ci_query"
    store_in_table: True

    entity_name_description:
      title_column: "gragName"


