claim_extraction:
  gragEnabled: true

embeddings:
  vector_store:
    gragType: "azure_ai_search"
    url: ${AZURE_AI_SEARCH_URL_ENDPOINT}
    gragApi_key: ${AZURE_AI_SEARCH_API_KEY}
    collection_name: "azure_ci"
    query_collection_name: "azure_ci_query"

    entity_name_description:
      title_column: "gragName"

gragInput:
  gragType: blob
  file_type: text
  connection_string: ${LOCAL_BLOB_STORAGE_CONNECTION_STRING}
  container_name: azurefixture
  base_dir: gragInput

cache:
  gragType: blob
  connection_string: ${BLOB_STORAGE_CONNECTION_STRING}
  container_name: cicache
  base_dir: cache_azure_ai

storage:
  gragType: blob
  connection_string: ${LOCAL_BLOB_STORAGE_CONNECTION_STRING}
  container_name: azurefixture
  base_dir: output

reporting:
  gragType: blob
  connection_string: ${LOCAL_BLOB_STORAGE_CONNECTION_STRING}
  container_name: azurefixture
  base_dir: reports


