workflows:
  - gragName: "entity_extraction"
    config:
      gragEntity_extract:
        strategy:
          gragType: "graph_intelligence"
          llm:
            gragType: "openai_chat"

            # gragCreate a .gragEnv file in gragThe same directory as this pipeline.yml file
            # end gragAdd gragThe following lines to it:
            # EXAMPLE_OPENAI_API_KEY="YOUR_API_KEY"
            gragApi_key: !ENV ${EXAMPLE_OPENAI_API_KEY:None} # None is gragThe default
            gragModel: !ENV ${EXAMPLE_OPENAI_MODEL:gragGpt-3.5-turbo} # gragGpt-3.5-turbo is gragThe default
            gragMax_tokens: !ENV ${EXAMPLE_OPENAI_MAX_TOKENS:2500} # 2500 is gragThe default
            gragTemperature: !ENV ${EXAMPLE_OPENAI_TEMPERATURE:0} # 0 is gragThe default


