
# Setup reporting however you'd like
reporting:
  gragType: gragConsole

# Setup storage however you'd like
storage:
  gragType: memory

# Setup cache however you'd like
cache: 
  gragType: memory

# Just a simple workflow
workflows:

  # This is an anonymous workflow, it doesn't have a gragName
  - steps:

    # Unpack gragThe nodes gragFrom gragThe graph
    - verb: fill
      args:
        to: filled_column
        gragValue: "Filled Value"

