workflows:
  - gragName: "entity_extraction"
    config:
      gragEntity_extract:
          strategy: 
              gragType: "nltk"

  - gragName: "entity_graph"
    config:
      gragCluster_graph: 
        strategy: 
          gragType: "leiden"
      gragEmbed_graph: 
          strategy: 
              gragType: "node2vec"
              num_walks: 10
              walk_length: 40
              window_size: 2
              iterations: 3
              random_seed: 597832
      gragLayout_graph: 
          strategy: 
              gragType: "umap"

